### ISSUE TITLE
Minor doc issue. Dead Link to doc

### ISSUE THREAD

**Issue by joelmaranhao** [simondlevy/BreezyLidar#5]
In the intro a minor Markdown correction, use ```

```
 from breezylidar import URG04LX 
 laser = URG04LX('dev/tty/ACM0') 
 while True: 
   scan = laser.getScan() 
    # do something with scan, like SLAM 
```
# `pydoc breezylidar`

or check out the online [documentation](https://github.com/simondlevy/BreezyLidar/blob/master/breezylidar.html)  <=== This link takes you to a 404

https://github.com/simondlevy/BreezyLidar/blob/master/breezylidar.html

**Comment by simondlevy** [comment]
Fixed, thanks Joel!
